restarters_menu:
  type: list
  default:
    'Talk, Restarters Talk,
    https://talk.restarters.net, vdm, self, keep, true, talk, restarters-talk-icon|Fixometer, Restarters Fixometer,
    https://restarters.net, vdm, self, keep, true, fixometer, restarters-fixometer-icon|Events, Restarters Events,
    https://restarters.net, vdm, self, keep, true, events, restarters-events-icon|Groups, Restarters Groups,
    https://restarters.net, vdm, self, keep, true, groups, restarters-groups-icon|Wiki, Restarters Wiki,
    https://wiki.restarters.net, vdm, self, keep, true, wiki, restarters-wiki-icon'
  description:
    en:
      'Comma delimited in this order: link text, link title, URL, view, target,
      hide on scroll, move to hamburger menu, link class name,icon<br><b>Link text:
      </b> The text for the link<br><b>Link title:</b> the text that shows when
      the link is hovered<br><b>URL:</b> The path for the link (can be
      relative)<br><b>View:</b> vdm = desktop and mobile, vdo = desktop only,
      vmo = mobile only<br><b>Target:</b> blank = opens in a new tab, self =
      opens in the same tab<br><b>Hide on scroll:</b> remove = hides the link
      when the title is expanded on topic pages keep = keeps the link visible
      even when the title is visible on topic pages<br> <b>Move to hamburger
      menu:</b> true = if the link is not visible in the header due to "vdo" or
      "vmo" (see above), put it in the hamburger menu instead<br><b>Link class
      name:</b> space-separated list of classes to apply to the link<br><b>Icon:</b> Ensure that the icon is available. In the format of restarters-<icon>'
